services:
  postgres:
    container_name: renthub-postgres
    image: postgres:15.10
    restart: unless-stopped
    environment:
      POSTGRES_USER: renthub
      POSTGRES_PASSWORD: renthub
      POSTGRES_DB: renthub_db
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
