# Generated by Django 5.1.7 on 2025-03-13 02:59

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundrybooking',
            name='voucher_image',
            field=models.ImageField(upload_to=core.models.laundry_voucher_upload_path, validators=[core.models.validate_image_file]),
        ),
    ]
