# Generated by Django 5.1.7 on 2025-03-23 05:35

from django.db import migrations, models
import core.models  # asegúrate de que tenga el import correcto si usas un método para `upload_to`

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_photo',
            field=models.ImageField(
                upload_to=core.models.contract_photo_upload_path,
                validators=[core.models.validate_image_file],
                blank=True,
                null=True
            ),
        ),
    ]
