# Generated by Django 5.1.7 on 2025-04-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified_email',
            field=models.BooleanField(default=False),
        ),
    ]
