# Generated by Django 5.1.7 on 2025-03-13 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_laundrybooking_voucher_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laundrybooking',
            name='room',
        ),
    ]
