# Generated by Django 5.1.6 on 2025-03-06 04:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_customuser_reference_name_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='payment_type',
            field=models.CharField(choices=[('rent', 'Rent Payment'), ('washing', 'Laundry Payment')], default='rent', max_length=10),
        ),
        migrations.CreateModel(
            name='LaundryBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time_slot', models.CharField(max_length=20)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laundry_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
