# Generated by Django 5.1.7 on 2025-05-03 20:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_is_verified_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_verified_email',
            new_name='is_verified',
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
